-- zad.1

SELECT COUNT(*) AS "Liczba pracowników"
FROM employee;

-- zad.2
SELECT COUNT(*) AS "Liczba pracowników bez numeru telefonu"
FROM employee
WHERE PHONE_EXT IS NULL;

-- zad.3
SELECT DISTINCT FIRST_NAME AS "Imiona pracowników"
FROM employee;

-- zad.4
SELECT COUNT(DISTINCT FIRST_NAME) AS "Liczba Imion"
FROM employee;

-- zad.5
SELECT COUNT(DISTINCT FIRST_NAME) AS "Liczba Imion na R"
FROM employee
WHERE FIRST_NAME LIKE 'R%';

-- ZAD.6
SELECT COUNT(*) AS "Liczba managerów zarabiających powyżej 60000"
FROM employee
WHERE JOB_CODE ='Mngr' AND SALARY >= 60000;

-- Zad.7
SELECT COUNT(DISTINCT JOB_COUNTRY) AS "Liczba Krajów"
FROM employee; 

-- Zad.8
SELECT COUNT(*) 
FROM country
WHERE COUNTRY LIKE 'A%'; 


-- Zad.9
SELECT COUNT(*) 
FROM country
WHERE COUNTRY LIKE '%and%'; 

-- zad.10
SELECT LAST_NAME,SALARY
FROM employee
WHERE JOB_COUNTRY = 'USA'; 

-- zad.11
SELECT SUM(SALARY), AVG(SALARY)  
FROM employee
WHERE JOB_COUNTRY = 'USA';

-- ZAD.12
SELECT COUNT(*) AS "Liczba pracowników", SUM(SALARY), JOB_COUNTRY
FROM employee
GROUP BY JOB_COUNTRY;

-- Zad.13
SELECT SUM(SALARY) AS "Suma zarobków", JOB_COUNTRY
FROM EMPLOYEE
GROUP BY JOB_COUNTRY 
ORDER BY 1 DESC;

-- ZAD.14

SELECT SUM(SALARY) AS "Suma zarobków", JOB_COUNTRY
FROM EMPLOYEE
GROUP BY JOB_COUNTRY 
HAVING COUNT(JOB_COUNTRY) >= 2
ORDER BY 1 DESC;

-- ZAD.15
SELECT SUM(SALARY) AS "Suma zarobków", SUM(SALARY * 0.19 - 1200) AS "Suma Podatku",JOB_COUNTRY
FROM EMPLOYEE
GROUP BY JOB_COUNTRY
ORDER BY 1 DESC;

-- zad.17!!!!!
SELECT DEPT_NO AS "Numer działu", MAX(SALARY) AS "MAXYmalne", MIN(SALARY) AS "MINIMALNE"
FROM employee
WHERE JOB_COUNTRY = 'USA' 
GROUP BY DEPT_NO
HAVING MIN(SALARY) >= 40000;

-- ZAD.18

SELECT COUNT(ORDER_STATUS) AS "Liczba transakcji" , SUM(TOTAL_VALUE)
FROM sales
WHERE ORDER_STATUS = 'open';

-- zad.19

SELECT CUST_NO, COUNT(CUST_NO), AVG(TOTAL_VALUE),SUM(TOTAL_VALUE) 
FROM sales
WHERE ORDER_DATE != '1993'
GROUP BY CUST_NO
ORDER BY 3 DESC;

-- zad.20
SELECT COUNT(DISTINCT SALARY),JOB_COUNTRY
FROM employee
GROUP BY JOB_COUNTRY;

-- ZAD.21
SELECT FIRST_NAME, COUNT(FIRST_NAME)
FROM EMPLOYEE
GROUP BY FIRST_NAME
HAVING COUNT(FIRST_NAME) >= 2;

-- ZAD.22
SELECT JOB_COUNTRY,JOB_CODE,COUNT(JOB_COUNTRY)
FROM EMPLOYEE
GROUP BY JOB_COUNTRY,JOB_CODE
HAVING COUNT(JOB_COUNTRY) >= 2;

-- ZAD.23
SELECT CONCAT_WS(',', FIRST_NAME,LAST_NAME,JOB_COUNTRY) AS "DATA"
FROM EMPLOYEE;

-- ZAD.24A
SELECT CONCAT_WS(',', FIRST_NAME,LAST_NAME,PHONE_EXT) AS "DATA"
FROM EMPLOYEE;

-- ZAD.24B
SELECT CONCAT( FIRST_NAME,' ',LAST_NAME,' ',IFNULL(PHONE_EXT,'')) AS "DATA"
FROM EMPLOYEE;

-- Zad.25

SELECT FIRST_NAME AS "Imie" , LAST_NAME AS "NAZWISKO" , EXTRACT(YEAR FROM HIRE_DATE )  AS "ROK URODZENIA" , SALARY / 12 AS "Zarobki"
FROM Employee;

-- Zad.26

SELECT * 
FROM Employee
WHERE EXTRACT(MONTH FROM HIRE_DATE) = 12; 

-- ZAD.27

SELECT *
FROM Employee
WHERE EXTRACT(DAY FROM HIRE_DATE) = 1 AND EXTRACT(YEAR FROM HIRE_DATE) = 1993;

-- ZAD.28

SELECT *
FROM Employee
WHERE DAYOFWEEK(HIRE_DATE) = 6;

-- Zad.29

SELECT EMP_NO, FIRST_NAME,LAST_NAME,HIRE_DATE,CURRENT_DATE, DATEDIFF(CURRENT_DATE,HIRE_DATE) 
FROM Employee;

-- ZAD.30

SELECT *
FROM employee
ORDER BY ISNULL(PHONE_EXT), CAST(PHONE_EXT AS INT) ASC;

-- ZAD.31

SELECT LOWER(FIRST_NAME) , UPPER(LAST_NAME)
FROM Employee;

-- zad.32

SELECT *
FROM Employee
WHERE UPPER(JOB_CODE) = "MNGR";

-- ZAD.33
SELECT *
FROM Employee
WHERE LAST_NAME LIKE "%do%" COLLATE UTF8MB4_BIN;

-- zad.dodatkowe

-- Posortowac tak jak w 30 bez uzycia isnull

SELECT *
FROM Employee
ORDER BY CASE WHEN PHONE_EXT IS NULL THEN 1 ELSE 0 END, CONVERT(PHONE_EXT, INT);   

 


















 









 

