-- zad.1

SELECT e.FIRST_NAME, e.LAST_NAME, d.DEPARTMENT
FROM Department d join employee e ON (e.DEPT_NO=d.DEPT_NO);

-- zad.2

SELECT e.FIRST_NAME, e.LAST_NAME, d.DEPARTMENT
FROM Department d join employee e ON (e.DEPT_NO=d.DEPT_NO)
WHERE e.JOB_COUNTRY = 'USA';

-- zad.3

SELECT D.*
FROM employee e join employee d ON (e.DEPT_NO=d.DEPT_NO)
WHERE e.FULL_NAME = 'Nelson, Robert';

-- ZAD.4

SELECT d.PROJ_NAME,e.FULL_NAME
FROM project d JOIN employee e ON (e.EMP_NO = d.TEAM_LEADER);

-- ZAD.5
SELECT d.PROJ_NAME,e.FULL_NAME
FROM project d LEFT JOIN employee e ON (e.EMP_NO = d.TEAM_LEADER);

-- ZAD.6

SELECT d.DEPT_NO,d.DEPARTMENT,COUNT(E.EMP_NO),IFNULL (AVG(E.SALARY),0),IFNULL (MIN(E.SALARY),0),IFNULL (MAX(E.SALARY),0),IFNULL (SUM(E.SALARY),0)
FROM employee e RIGHT JOIN department d ON (d.DEPT_NO=e.DEPT_NO)
GROUP BY d.DEPT_NO,department; 

-- ZAD.7

SELECT E.LAST_NAME,E.FIRST_NAME,E.DEPT_NO ,E.SALARY, AVG(d.SALARY),MIN(d.SALARY), MAX(d.SALARY),SUM(d.SALARY)
FROM employee e JOIN employee d ON (e.DEPT_NO=d.DEPT_NO)
GROUP BY e.DEPT_NO,e.FIRST_NAME,e.LAST_NAME,e.SALARY,e.EMP_NO;

-- ZAD.8

SELECT E.LAST_NAME,E.FIRST_NAME,E.DEPT_NO ,E.SALARY,SUM(d.SALARY),e.SALARY * 100 / SUM(d.SALARY)
FROM employee e JOIN employee d ON (e.DEPT_NO=d.DEPT_NO)
GROUP BY e.DEPT_NO,e.FIRST_NAME,e.LAST_NAME,e.SALARY,e.EMP_NO; 

-- zad.9 

SELECT E.LAST_NAME,E.FIRST_NAME,E.DEPT_NO ,E.SALARY,SUM(d.SALARY), e.SALARY * 100 / SUM(d.SALARY)
FROM employee e JOIN employee d ON (e.DEPT_NO=d.DEPT_NO)
GROUP BY e.DEPT_NO,e.FIRST_NAME,e.LAST_NAME,e.SALARY,e.EMP_NO
HAVING e.SALARY * 100 / SUM(d.SALARY) >= ALL(SELECT e.SALARY * 100 / SUM(d.SALARY) FROM employee e JOIN employee d ON (e.DEPT_NO=d.DEPT_NO) GROUP BY e.DEPT_NO,e.FIRST_NAME,e.LAST_NAME,e.SALARY,e.EMP_NO); 

-- zad.9b

SELECT E.LAST_NAME,E.FIRST_NAME,E.DEPT_NO ,E.SALARY,SUM(d.SALARY), e.SALARY * 100 / SUM(d.SALARY)
FROM employee e JOIN employee d ON (e.DEPT_NO=d.DEPT_NO)
GROUP BY e.DEPT_NO,e.FIRST_NAME,e.LAST_NAME,e.SALARY,e.EMP_NO
HAVING e.SALARY * 100 / SUM(d.SALARY) >= ALL(SELECT e.SALARY * 100 / SUM(d.SALARY) FROM employee e JOIN employee d ON (e.DEPT_NO=d.DEPT_NO) WHERE E.DEPT_NO = D.DEPT_NO GROUP BY e.DEPT_NO,e.FIRST_NAME,e.LAST_NAME,e.SALARY,e.EMP_NO);

-- ZAD.10

SELECT  d.DEPT_NO,d.BUDGET,IFNULL((D.BUDGET) - SUM(e.SALARY),0) 
FROM employee e right join department d ON(e.DEPT_NO = d.DEPT_NO)
GROUP BY d.DEPT_NO, d.BUDGET;

-- zad.11
SELECT COUNT(DISTINCT DEPT_NO), c.COUNTRY
FROM employee e RIGHT JOIN country c ON (e.JOB_COUNTRY = c.COUNTRY) 
GROUP BY c.country;

-- zad.12
SELECT SUM(e.SALARY),d.DEPT_NO, d.DEPARTMENT
FROM employee e JOIN department d ON (e.DEPT_NO =d.DEPT_NO )
WHERE e.JOB_CODE = 'mngr'
GROUP BY d.DEPT_NO, d.DEPARTMENT;

-- zad.13

SELECT COUNT(*),YEAR(HIRE_DATE)
FROM employee e
GROUP BY YEAR (e.HIRE_DATE);

-- zad.14 
SELECT COUNT(e.EMP_NO),YEAR(e.HIRE_DATE),d.DEPARTMENT
FROM employee e right join department d ON (e.DEPT_NO = d.DEPT_NO)
GROUP BY YEAR (e.HIRE_DATE),d.DEPARTMENT;

-- zad.15
SELECT COUNT(*)
FROM employee e1 JOIN employee e2 ON(e1.SALARY > e2.SALARY) 
WHERE e2.FULL_NAME ='Brown, Kelly';

-- ZAD.16
SELECT COUNT(*)
FROM employee e1 JOIN employee e2 ON(e1.SALARY > e2.SALARY) 
WHERE e2.FULL_NAME ='Brown, Kelly'AND e1.DEPT_NO = e2.DEPT_NO;

-- zad.17 a)
SELECT COUNT(e1.EMP_NO),e2.FULL_NAME
FROM employee e1 RIGHT JOIN employee e2 ON(e1.SALARY > e2.SALARY) 
GROUP BY e2.EMP_NO,e2.FULL_NAME
ORDER BY 1;

-- zad.17 B) 
SELECT COUNT(e1.EMP_NO),e2.FULL_NAME,e2.DEPT_NO
FROM employee e1 RIGHT JOIN employee e2 ON(e1.SALARY > e2.SALARY AND e1.DEPT_NO = e2.DEPT_NO ) 
GROUP BY e2.EMP_NO,e2.FULL_NAME,e2.DEPT_NO
ORDER BY 3,1;
 







