-- Zad.1

SELECT AVG(SALARY),MAX(SALARY),MIN(SALARY)
FROM Employee;

-- Zad.2

SELECT FIRST_NAME,LAST_NAME,DEPT_NO,SALARY
FROM Employee
WHERE SALARY = (SELECT MAX(SALARY) FROM Employee) OR SALARY = (SELECT MIN(SALARY) FROM Employee);

-- ZAD.3

SELECT FIRST_NAME,LAST_NAME,DEPT_NO,SALARY
FROM Employee
WHERE HIRE_DATE = (SELECT MAX(HIRE_DATE) FROM Employee) OR HIRE_DATE = (SELECT MIN(HIRE_DATE) FROM Employee);

-- zad.4

SELECT *
FROM Employee
WHERE DEPT_NO =(SELECT DEPT_NO FROM Employee WHERE FULL_NAME ='Nelson, Robert');

-- ZAD.5A

SELECT AVG(SALARY)
FROM Employee;

-- ZAD.5B

SELECT *
FROM Employee
WHERE SALARY > (SELECT AVG(SALARY) FROM Employee);

-- zad.6

SELECT *
FROM Employee
WHERE DEPT_NO = '623' AND SALARY < (SELECT AVG(SALARY) FROM Employee WHERE DEPT_NO = '623');

-- ZAD.7

SELECT DEPT_NO,AVG(SALARY)
FROM Employee
GROUP BY DEPT_NO
ORDER BY 2 ASC ;

-- ZAD.8

SELECT DEPT_NO,AVG(SALARY)
FROM Employee
GROUP BY DEPT_NO
HAVING 100000 < AVG(SALARY);

-- zad.9

SELECT DEPT_NO,AVG(SALARY)
FROM Employee
WHERE JOB_COUNTRY = 'USA'
GROUP BY DEPT_NO
HAVING 100000 < AVG(SALARY);

-- ZAD.10

SELECT FULL_NAME,SALARY,DEPT_NO
FROM Employee d
WHERE SALARY = (SELECT MAX(SALARY) FROM Employee e WHERE d.DEPT_NO = e.DEPT_NO );

-- ZAD.11

SELECT FULL_NAME,SALARY,DEPT_NO
FROM Employee d
WHERE SALARY = (SELECT MAX(SALARY) FROM Employee e WHERE d.DEPT_NO = e.DEPT_NO ) OR SALARY = (SELECT MIN(SALARY) FROM Employee e WHERE d.DEPT_NO = e.DEPT_NO )
ORDER BY 2 ASC;

-- ZAD.12

SELECT DEPT_NO
FROM Employee d
GROUP BY DEPT_NO
HAVING COUNT(DEPT_NO) >= 4; 

-- ZAD.13

SELECT DEPT_NO, d.DEPARTMENT
FROM Department d
WHERE EXISTS (SELECT DEPT_NO 
					FROM Employee g 
					WHERE g.SALARY > 100000 AND g.DEPT_NO = D.DEPT_NO); 
					
-- ZAD.14

SELECT DEPT_NO, d.DEPARTMENT
FROM Department d
WHERE 2 < (SELECT COUNT(SALARY) FROM Employee g WHERE g.SALARY > 100000 AND g.DEPT_NO = d.DEPT_NO);

-- ZAD.15

SELECT DEPT_NO, d.DEPARTMENT
FROM Department d
WHERE 2 <= (SELECT COUNT(SALARY) FROM Employee g WHERE g.SALARY < 100000 AND g.JOB_CODE ='eng' AND g.DEPT_NO = d.DEPT_NO);

-- zad.16

SELECT DEPT_NO, d.DEPARTMENT
FROM Department d
WHERE (SELECT COUNT(*) FROM Employee g WHERE JOB_COUNTRY = 'USA' AND g.DEPT_NO = d.DEPT_NO) = 0;

-- ZAD.17

SELECT DEPT_NO, d.DEPARTMENT
FROM Department d
WHERE (SELECT g.SALARY FROM Employee g WHERE g.EMP_NO = d.MNGR_NO) > 90000;







